import { Npc } from "..";

export const BAN_LAND_NPCS = {
	forestWizard: {
		name: "Forest Wizard",
		health: 100,
		reward: {
			bans: 1,
			currency: 35,
			currencyType: "coins",
			experience: 10,
		},
		rank: 1,
		isBoss: false,
	},
	desertBandit: {
		name: "Desert Bandit",
		health: 200,
		reward: {
			bans: 2,
			currency: 60,
			currencyType: "coins",
			experience: 20,
		},
		rank: 1,
		isBoss: false,
	},
	floralGirl: {
		name: "Floral Girl",
		health: 400,
		reward: {
			bans: 4,
			currency: 120,
			currencyType: "coins",
			experience: 40,
		},
		rank: 1,
		isBoss: false,
	},
	beeKing: {
		name: "Bee King",
		health: 800,
		reward: {
			bans: 8,
			currency: 270,
			currencyType: "coins",
			experience: 80,
		},
		rank: 2,
		isBoss: false,
	},
	iceSkier: {
		name: "Ice Skier",
		health: 1_600,
		reward: {
			bans: 16,
			currency: 810,
			currencyType: "coins",
			experience: 160,
		},
		rank: 3,
		isBoss: false,
	},
	beachBoy: {
		name: "Beach Boy",
		health: 3_200,
		reward: {
			bans: 32,
			currency: 1_215,
			currencyType: "coins",
			experience: 800,
		},
		rank: 4,
		isBoss: false,
	},
	sparkletimeKing: {
		name: "Sparkletime King",
		health: 6_400,
		reward: {
			bans: 64,
			currency: 2_100,
			currencyType: "coins",
			experience: 2_000,
		},
		rank: 5,
		isBoss: false,
	},
	miningGuy: {
		name: "Mining Guy",
		health: 12_800,
		reward: {
			bans: 128,
			currency: 4_200,
			currencyType: "coins",
			experience: 6_000,
		},
		rank: 6,
		isBoss: false,
	},
	lavaLord: {
		name: "Lava Lord",
		health: 25_600,
		reward: {
			bans: 256,
			currency: 8_400,
			currencyType: "coins",
			experience: 10_000,
		},
		rank: 7,
		isBoss: false,
	},
	enchantedGolem: {
		name: "Enchanted Golem",
		health: 51_200,
		reward: {
			bans: 512,
			currency: 16_800,
			currencyType: "coins",
			experience: 20_000,
		},
		rank: 8,
		isBoss: false,
	},
	toxicSparkletimeKing: {
		name: "Toxic Sparkletime King",
		health: 102_400,
		reward: {
			bans: 1024,
			currency: 33_600,
			currencyType: "coins",
			experience: 40_000,
		},
		rank: 9,
		isBoss: false,
	},
	neonJester: {
		name: "Neon Jester",
		health: 204800,
		reward: {
			bans: 2048,
			currency: 67_200,
			currencyType: "coins",
			experience: 80_000,
		},
		rank: 10,
		isBoss: false,
	},

	// Bosses
	mushroomKing: {
		name: "Mushroom King",
		health: 300,
		reward: {
			bans: 3,
			currency: 105,
			currencyType: "coins",
			experience: 120,
		},
		rank: 1,
		isBoss: true,
	},
	desertScout: {
		name: "Desert Scout",
		health: 600,
		reward: {
			bans: 6,
			currency: 180,
			currencyType: "coins",
			experience: 240,
		},
		rank: 1,
		isBoss: true,
	},
	magicFloralMan: {
		name: "Magic Floral Man",
		health: 1_200,
		reward: {
			bans: 12,
			currency: 360,
			currencyType: "coins",
			experience: 480,
		},
		rank: 1,
		isBoss: true,
	},
	onett: {
		name: "Onett",
		health: 2_400,
		reward: {
			bans: 24,
			currency: 810,
			currencyType: "coins",
			experience: 945,
		},
		rank: 2,
		isBoss: true,
	},
	iceGolem: {
		name: "Ice Golem",
		health: 4_800,
		reward: {
			bans: 48,
			currency: 2_430,
			currencyType: "coins",
			experience: 1_875,
		},
		rank: 3,
		isBoss: true,
	},
	pufferfishKing: {
		name: "Pufferfish King",
		health: 9_600,
		reward: {
			bans: 96,
			currency: 3_645,
			currencyType: "coins",
			experience: 3_750,
		},
		rank: 4,
		isBoss: true,
	},
	pastelGuardian: {
		name: "Pastel Guardian",
		health: 19_200,
		reward: {
			bans: 192,
			currency: 6_300,
			currencyType: "coins",
			experience: 7_500,
		},
		rank: 5,
		isBoss: true,
	},
	elementalKing: {
		name: "Elemental King",
		health: 38_400,
		reward: {
			bans: 384,
			currency: 12_600,
			currencyType: "coins",
			experience: 15_000,
		},
		rank: 6,
		isBoss: true,
	},
	headlessDoombringer: {
		name: "Headless Doombringer",
		health: 76_800,
		reward: {
			bans: 768,
			currency: 25_200,
			currencyType: "coins",
			experience: 30_000,
		},
		rank: 7,
		isBoss: true,
	},
	udzal: {
		name: "Ud'zal",
		health: 153_600,
		reward: {
			bans: 1_536,
			currency: 50_400,
			currencyType: "coins",
			experience: 60_000,
		},
		rank: 8,
		isBoss: true,
	},
	toxicWastelander: {
		name: "Toxic Wastelander",
		health: 307_200,
		reward: {
			bans: 3_072,
			currency: 100_800,
			currencyType: "coins",
			experience: 120_000,
		},
		rank: 9,
		isBoss: true,
	},
	prince: {
		name: "Prince",
		health: 614_400,
		reward: {
			bans: 6_144,
			currency: 201_600,
			currencyType: "coins",
			experience: 240_000,
		},
		rank: 10,
		isBoss: true,
	},
} satisfies Record<string, Npc>;
