-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		currencies = {
			gold = "rbxassetid://9591269212",
		},
		misc = {
			click = "rbxassetid://9619404897",
		},
	},
}