declare namespace assetIds {
	const images: {
		Exit: string;
		vectors: {
			Inventory: string;
			Medal: string;
			FewGems: string;
			Shield: string;
			Sword: string;
			GemBag: string;
			Settings: string;
			Codes: string;
			PetPaw: string;
			CyberToken: string;
			Coin: string;
			Teleport: string;
			SpinWheel: string;
			Rewards: string;
			Trading: string;
			GemVault: string;
			Gem: string;
			GemChest: string;
			Clover: string;
		};
		maps: {
			"Ban Land": {
				world: string;
			};
		};
		buttons: {
			"back arrow": string;
			"red toggle button": string;
			"down button": string;
			"green button": string;
			"green toggle button": string;
			"teal button": string;
			exit: string;
			"red button": string;
			"long green button": string;
			"forward arrow": string;
			"purple button": string;
		};
		currencies: {
			gems: string;
			coins: string;
		};
		ui: {
			teleportation: {
				"Ban Land": string;
				"Ban Land Locked": string;
				Beach: string;
				"Beach Locked": string;
				"Candy Land": string;
				"Candy Land Locked": string;
				Desert: string;
				"Desert Locked": string;
				Forest: string;
				"Forest Locked": string;
				Honeycomb: string;
				"Honeycomb Locked": string;
				"Ice Land": string;
				"Ice Land Locked": string;
				"Lava Lands": string;
				"Lava Lands Locked": string;
				"Sunflower Field": string;
				"Sunflower Field Locked": string;
				"The Mines": string;
				"The Mines Locked": string;
				background: string;
				go: string;
			};
			egg: {
				background: string;
				"pet frame": string;
				delete: string;
			};
			"weapon shop": {
				locked: string;
				delete: string;
				"purchase button": string;
				"weapon info background": string;
			};
			index: {
				Off: string;
				footerNotice: string;
				Claim: string;
				extra: string;
				showExtraStats: string;
				"view challenges": string;
				returnToSelection: string;
				background: string;
				sidebar: string;
				eggBackground: string;
				view: string;
			};

			inventory: {
				petSummary: string;
				background: string;
				icons: {
					boosts: string;
					pets: string;
					talismans: string;
					titles: string;
					weapons: string;
				};
				"info sidebar": string;
				pets: {
					bottombar: string;
					"delete-sidebar": string;
					deleteIndicator: string;
					"equipped checkmark": string;
					"function button": string;
					gamepassPrompt: string;
					"inventory size counter icon": string;
					locked: string;
					maximize: string;
					"multi-delete disabled": string;
					"multi-delete enabled": string;
					"pet counter icon": string;
					search: string;
					shrink: string;
					sort: string;
					topbar: string;
					"unequip all": string;
				};
			};
			"rank upgrade": {
				cancel: string;
				background: string;
				maxRank: string;
				upgrade: string;
			};
			zones: {
				background: string;
				purchase: string;
				cancel: string;
			};
			"update log": {
				"update log": string;
				background: string;
			};
			hud: {
				"interface button": string;
				shop: string;
				upgrade: string;
				"viewer background": string;
				icons: {
					items: string;
					options: string;
					codes: string;
					wheel: string;
					rewards: string;
					teleport: string;
					trading: string;
				};
				"rank fill": string;
			};
			autoDelete: {
				background: string;
				"long green button": string;
				"long red button": string;
			};
			codes: {
				input: string;
				background: string;
			};
			equip: {
				unequipped: string;
				keybind: string;
				toolTp: string;
				background: string;
				equipped: string;
			};
			talismanTower: {
				sidebar: string;
				background: string;
			};
			quests: {
				"world background": string;
				"world entry background": string;
				"quests background": string;
				"entry background": string;
			};
			settings: {
				"setting background": string;
				background: string;
			};
			levelup: {
				LevelUp: string;
			};
		};
		decals: {
			boosts: {
				luck: string;
			};
			pets: {
				"Void Desert Scorpilord": string;
				"Desert Pegasus": string;
				Piggy: string;
				"Desert Demon": string;
				"Radiant Desert Pegasus": string;
				"Corrupt Bear": string;
				"Void Desert Demon": string;
				"Void Corrupt Bear": string;
				"Royal Bunny": string;
				"Void Royal Dragon": string;
				"Radiant City Defender": string;
				"Corrupt Deer": string;
				"Void Royal Bunny": string;
				"Void Queen Bee": string;
				Bunny: string;
				"Void City Angel": string;
				"Radiant Bunny": string;
				"Gummy Bee": string;
				"Radiant Armored Guard": string;
				"Radiant Hellfire Ball": string;
				"Void Molten Kitty": string;
				"Void Molten Wraith": string;
				"Radiant Desert Angel": string;
				"Radiant Gummy Kitty": string;
				"Molten Squirrel": string;
				"Armored Doggy": string;
				"Molten Bunny": string;
				"Desert Spider": string;
				"Void Piggy": string;
				"Corrupt Doggy": string;
				"Void Molten Leviathan": string;
				"Radiant Mystical Bee": string;
				"Gummy Dragon": string;
				"Radiant Cyber Bear": string;
				"Desert Angel": string;
				"Void Cyber Angel": string;
				"Radiant Corrupt Bear": string;
				"Void Molten Destroyer": string;
				"Void Bunny": string;
				"Void Armored Angel-1": string;
				"City Bunny": string;
				"Void Molten Bunny": string;
				"Void Molten Blob": string;
				"Radiant Desert Demon": string;
				"Molten Pegasus": string;
				"Void Desert Ram": string;
				Coreye: string;
				"Evil Bee": string;
				"Void Coreye": string;
				"Cybernetic Guard": string;
				"Void City Defender": string;
				"Void Evil Bee": string;
				"Armored Angel": string;
				"Radiant Armored Bunny": string;
				"Radiant Molten Pegasus": string;
				"Cyber Bear": string;
				"Radiant Cyber Angel": string;
				"Radiant Armored Dragon": string;
				"Bunny Bee": string;
				"City Defender": string;
				"Cyber Bunny": string;
				"Void Ice Cream Pop": string;
				"Void Honey Bee": string;
				"Void Hellfire Hound": string;
				"Gummy Bear": string;
				Doggy: string;
				"Void Hellfire Ball": string;
				"Void Corrupt Demon": string;
				"Radiant Gummy Striker": string;
				"Radiant Honey Bee": string;
				"Molten Leviathan": string;
				"Radiant City Angel": string;
				"Radiant Dinosaur Bee": string;
				"Radiant Desert Ram": string;
				"Gummy Striker": string;
				"Radiant BIG Royal Bunny": string;
				"Radiant Ice Cream Pop": string;
				"Void Gummy Striker": string;
				"Void Gummy Kitty": string;
				"Radiant Corrupt Bunny": string;
				"Void Gummy Bunny-1": string;
				"Hellfire Ball": string;
				"Void Gummy Dragon": string;
				"Armored Deer": string;
				"Doggy Bee": string;
				"Hellfire Hound": string;
				"Desert Scorpilord": string;
				"Void Gummy Wyvern": string;
				"City Deer": string;
				"City Angel": string;
				"Bumble Bee": string;
				"Void Gummy Bunny": string;
				"Void Gummy Bee": string;
				"Radiant City Deer": string;
				"Armored Bunny": string;
				"Void Bunny Bee": string;
				"Void Molten Doggy": string;
				"Void Doggy": string;
				"Void Desert Wraith": string;
				"Radiant City Bunny": string;
				"Void Dinosaur Bee": string;
				"Radiant Cybernetic Destroyer": string;
				"Void Desert Spider": string;
				"Void Corrupted Titan": string;
				"Void Desert Pegasus": string;
				"Void Corrupt Pegasus": string;
				"Corrupt Demon": string;
				"Void Desert Dragon": string;
				"Radiant Armored Kitty": string;
				Deer: string;
				"Radiant Armored Pegasus": string;
				"Radiant Royal Dragon": string;
				"Void Deer": string;
				"Radiant Cybernetic Dementor": string;
				"Cybernetic Phoenix": string;
				"Void Corrupt Doggy": string;
				"Void Cybernetic Phoenix": string;
				"Radiant Gummy Bee": string;
				"Void Cybernetic Dementor": string;
				"Void Cybernetic Guard": string;
				"Radiant City Kitty": string;
				"Void Cybernetic Destroyer": string;
				"Desert Dragon": string;
				"Void Cyber Pegasus": string;
				"Mystical Bee": string;
				"Void Cyber Kitty": string;
				"Armored Kitty": string;
				"Cybernetic Destroyer": string;
				"Radiant Molten Destroyer": string;
				"Radiant Cybernetic Phoenix": string;
				"Void Cyber Bear": string;
				"Void Doggy Bee": string;
				"Radiant Bumble Bee": string;
				"Armored Spartan": string;
				"Desert Wraith": string;
				"Radiant Corrupt Pegasus": string;
				"Molten Doggy": string;
				"Armored Dragon": string;
				"Corrupt Hyperhalo": string;
				"Radiant Doggy Bee": string;
				"Radiant Corrupt Deer": string;
				"Molten Destroyer": string;
				"Void Armored Spartan": string;
				"Cyber Angel": string;
				"Queen Bee": string;
				"Radiant Gummy Dragon": string;
				"Gummy Wyvern": string;
				"Void Corrupted Overseer": string;
				"Void Corrupt Duke": string;
				Kitty: string;
				"Void Corrupt Deer": string;
				"Void Corrupt Bunny": string;
				"Cyber Doggy": string;
				"Armored Guard": string;
				"Radiant Royal Bunny": string;
				"Void Royal Pegasus": string;
				"Radiant Cyber Bunny": string;
				"Honey Bee": string;
				"Void Kitty": string;
				"Void City Kitty": string;
				"Void Molten Pegasus": string;
				"Void City Deer": string;
				"Corrupted Overseer": string;
				"Void City Bunny": string;
				"Void City Doggy": string;
				"Void Gumdrop": string;
				"Radiant Desert Spider": string;
				"Radiant Gumdrop": string;
				"Armored Pegasus": string;
				"Cybernetic Dementor": string;
				"Cyber Pegasus": string;
				"Void Armored Pegasus": string;
				"Radiant Doggy": string;
				"Void Armored Guard": string;
				"Void Armored Doggy": string;
				"Radiant Desert Dragon": string;
				"Radiant Corrupt Doggy": string;
				"Void Armored Bunny": string;
				"Void Armored Angel": string;
				"Radiant Gummy Bear": string;
				"Radiant Armored Deer": string;
				Gumdrop: string;
				"Royal Dragon": string;
				"Corrupt Pegasus": string;
				"Radiant City Doggy": string;
				"Radiant Queen Bee": string;
				"Dinosaur Bee": string;
				"Radiant Cyber Pegasus": string;
				"Radiant Corrupted Overseer": string;
				"Royal Pegasus": string;
				"Gummy Kitty": string;
				"Radiant Molten Wraith": string;
				"Radiant Gummy Bunny": string;
				"Radiant Molten Leviathan": string;
				"Radiant Molten Bunny": string;
				"Radiant Molten Doggy": string;
				"Void Cyber Doggy": string;
				"Radiant Molten Kitty": string;
				"Radiant Cyber Kitty": string;
				"Corrupt Duke": string;
				"Radiant Molten Blob": string;
				"Radiant Hellfire Hound": string;
				"Radiant Corrupt Hyperhalo": string;
				"Void Mystical Bee": string;
				"Desert Ram": string;
				"Radiant Gummy Wyvern": string;
				"Radiant Coreye": string;
				"City Kitty": string;
				"Radiant Gummy Doggy": string;
				"Radiant Molten Squirrel": string;
				"Radiant Evil Bee": string;
				"Void Corrupt Hyperhalo": string;
				"Void Armored Kitty": string;
				"Radiant Desert Wraith": string;
				"Void Bumble Bee": string;
				"Radiant Desert Scorpilord": string;
				"Radiant Deer": string;
				"Void Cyber Bunny": string;
				"Radiant Corrupt Demon": string;
				"Radiant Cybernetic Guard": string;
				"Radiant Cyber Doggy": string;
				"Radiant Corrupt Duke": string;
				"Radiant Piggy": string;
				"BIG Royal Bunny": string;
				"Radiant Kitty": string;
				"Radiant Corrupted Titan": string;
				"Void Armored Deer": string;
				"Void Gummy Bear": string;
				"Molten Wraith": string;
				"City Doggy": string;
				"Void Pegasus Bee": string;
				"Radiant Armored Spartan": string;
				"Radiant Armored Doggy": string;
				"Radiant Pegasus Bee": string;
				"Radiant Armored Angel": string;
				"Gummy Doggy": string;
				"Gummy Bunny": string;
				"Radiant Bunny Bee": string;
				"Molten Kitty": string;
				DecalTemplate: string;
				"Molten Blob": string;
				"Void Gummy Doggy": string;
				"Ice Cream Pop": string;
				"Pegasus Bee": string;
				"Void Molten Squirrel": string;
				"Corrupt Bunny": string;
				"Void Desert Angel": string;
				"Cyber Kitty": string;
				"Void BIG Royal Bunny": string;
				"Corrupted Titan": string;
				"Radiant Royal Pegasus": string;
			};
			eggs: {
				Honeycomb: string;
				Starter: string;
				Candy: string;
				Molten: string;
				Desert: string;
			};
			worlds: {
				"Ban Land": string;
			};
		};
		ranks: {
			friendly: {
				"9": string;
				"8": string;
				"4": string;
				"20": string;
				"1": string;
				"5": string;
				"3": string;
				"2": string;
				"19": string;
				"18": string;
				"7": string;
				"6": string;
				"14": string;
				"15": string;
				"16": string;
				"17": string;
				"13": string;
				"12": string;
				"11": string;
				"10": string;
			};
			enemy: {
				regular: {
					Diamond: string;
					Silver: string;
					Gold: string;
					Bronze: string;
					Ruby: string;
				};
				boss: {
					Diamond: string;
					Silver: string;
					Gold: string;
					Bronze: string;
					Ruby: string;
				};
			};
		};
	};
}

export = assetIds;
