declare namespace assetIds {
	const images: {
		Exit: string;
		maps: {
			"Ban Land": {
				world: string;
			};
		};
		buttons: {
			"back arrow": string;
			"red toggle button": string;
			"down button": string;
			"green button": string;
			"green toggle button": string;
			"teal button": string;
			exit: string;
			"red button": string;
			"long green button": string;
			"forward arrow": string;
			"purple button": string;
		};
		decals: {
			leaderboard: {
				bans: string;
				eggs: string;
			};
			boosts: {
				BigCrateBundle: string;
				ExtremeExperienceBundle: string;
				luck: string;
			};
			UpdateLog: string;
			pets: {
				"Void Desert Scorpilord": string;
				"Radiant Gear Cat": string;
				"Desert Demon": string;
				"Radiant Desert Pegasus": string;
				"Corrupt Bear": string;
				"Void Desert Demon": string;
				"Radiant City Defender": string;
				"Corrupt Deer": string;
				"Radiant Gear Bee": string;
				Bunny: string;
				"Gummy Bee": string;
				"Radiant Doggy Bee": string;
				"Void Molten Kitty": string;
				"Void 500K Bunny": string;
				"Radiant Gummy Kitty": string;
				"Molten Squirrel": string;
				"Armored Doggy": string;
				"Radiant 500K Dominus": string;
				"Void Piggy": string;
				"Corrupt Doggy": string;
				"Radiant Mystical Bee": string;
				"Gummy Dragon": string;
				"Desert Angel": string;
				"Void Bunny": string;
				"Void Gummy Bunny": string;
				"Radiant 500k Wraith": string;
				"Void Honey Bee": string;
				"Hellfire Infernum": string;
				"Void Gear Doggy": string;
				Coreye: string;
				"Evil Bee": string;
				"Cybernetic Guard": string;
				"Void City Defender": string;
				"Armored Angel": string;
				"Void Dark Angel": string;
				"Radiant Angel": string;
				"Radiant All Seeing Jester": string;
				"Void Cyber Pegasus": string;
				"Radiant Armored Dragon": string;
				"Bunny Bee": string;
				"Radiant Steambot": string;
				"Cyber Pegasus": string;
				"Gear Bee": string;
				"Gummy Bear": string;
				Doggy: string;
				"Void Corrupt Demon": string;
				"Radiant Honey Bee": string;
				"Radiant Gummy Bunny": string;
				"Developer Gummy Bunny": string;
				"Void Armored Angel": string;
				"Radiant BIG Royal Bunny": string;
				"Radiant Molten Leviathan": string;
				"Radiant Radioactive Gryphon": string;
				"Radiant Mother Earth": string;
				"Radiant Jester Defender": string;
				"Doggy Bee": string;
				"Void 500K Cat": string;
				"Void Gummy Wyvern": string;
				"City Deer": string;
				"Radiant 500K Dragon": string;
				"All Seeing Jester": string;
				"Desert Spider": string;
				"500K Archmage": string;
				"Radiant PeaceKeeper": string;
				"Radiant City Bunny": string;
				"Void Dinosaur Bee": string;
				"Void Angel": string;
				"Radiant Byte": string;
				"Corrupt Demon": string;
				"Void 500K Angel": string;
				Hychampion: string;
				"Molten Wraith": string;
				"Void Corrupt Doggy": string;
				"500K Cat": string;
				"Void Cybernetic Dementor": string;
				"Radiant City Kitty": string;
				"Radiant Hellfire Infernum": string;
				"Void Cyber Bear": string;
				"Void Doggy Bee": string;
				"Radiant Bumble Bee": string;
				"Armored Spartan": string;
				"Desert Wraith": string;
				"Radiant Corrupt Pegasus": string;
				"Molten Doggy": string;
				"Armored Dragon": string;
				"Radiant Mida": string;
				"Radiant Corrupt Deer": string;
				"Jester Doggy": string;
				"Void Corrupt Bunny": string;
				"Gummy Wyvern": string;
				Kitty: string;
				"500K Bunny": string;
				"Cyber Doggy": string;
				"Radiant Royal Bunny": string;
				"Jester Defender": string;
				"500K Ram": string;
				"Shade Glider": string;
				"Corrupted Overseer": string;
				"Radiant Gear Bunny": string;
				"Radiant Jester Red Panda": string;
				"Void Gummy Striker": string;
				"Armored Pegasus": string;
				"Radiant Jester Diamond": string;
				"Void Jester Narwhal": string;
				"Gear Cat": string;
				"Clown Dragon": string;
				"500K Dragon": string;
				"Radiant Radioactive Imp": string;
				"Void Gummy Bee": string;
				"Void Developer Gummy Bunny": string;
				"Void Supreme Dove": string;
				"Prime Royal": string;
				"Void Jester Diamond": string;
				"Void Chromatic Obliterator": string;
				"Radiant Supreme Dove": string;
				"Radiant Doggy": string;
				"Radiant Jester Ghost": string;
				"Void Steambot": string;
				"Void Hychampion": string;
				"Void Shattered Diety": string;
				"Void Shade Glider": string;
				"Gear Striker": string;
				"Radiant Cyber Kitty": string;
				"Void Cyber Bunny": string;
				"Void Seekstress": string;
				"Radiant Quiet Angel": string;
				"Void Royal Pegasus": string;
				"Void Mystical Bee": string;
				"Radiant Corrupt Bear": string;
				"Void Queen Bee": string;
				"Void Mother Earth": string;
				"Jester Diamond": string;
				"Void Radioactive Phoenix": string;
				"Void Cyber Kitty": string;
				"Void Radioactive Gryphon": string;
				"Void Quiet Angel": string;
				"Void Armored Kitty": string;
				"Radiant Dark Angel": string;
				"Void Royal Bunny": string;
				"Void Prime Royal": string;
				"Void Pegasus Bee": string;
				Siphon: string;
				"Radiant Corrupt Demon": string;
				"Void Jester Angel": string;
				"Hellfire Dragon": string;
				"Void Gear Dominus": string;
				"Void Corrupt Deer": string;
				"BIG Royal Bunny": string;
				"Radiant Kitty": string;
				"Void Radioactive Vision": string;
				"Void Armored Deer": string;
				"Void Gummy Bear": string;
				"Void Jester Defender": string;
				"Radiant 500K Cat": string;
				"Radiant 500K Archmage": string;
				"Void Molten Wraith": string;
				"Void Mida": string;
				"Radiant Pegasus Bee": string;
				"Radiant Shattered Diety": string;
				"Void Molten Leviathan": string;
				"Void Molten Doggy": string;
				"Radiant Bunny Bee": string;
				"Corrupt Pegasus": string;
				"Void Molten Bunny": string;
				"Void Desert Dragon": string;
				"Void Minty Kitty": string;
				"Ice Cream Pop": string;
				"Pegasus Bee": string;
				"Void Molten Squirrel": string;
				"Void Kitty": string;
				"Radiant Jester Narwhal": string;
				Byte: string;
				"Void BIG Royal Bunny": string;
				"Void Jester Red Panda": string;
				"Radiant Royal Pegasus": string;
				"Void Gear Bee": string;
				"Desert Pegasus": string;
				"500K Angel": string;
				"Radiant D I V I N E": string;
				"Gear Destroyer": string;
				"Radiant Armored Doggy": string;
				"Void 500k Wraith": string;
				"Void Eternal Gear": string;
				"Jester Angel": string;
				"Jester Ghost": string;
				"Radiant Minty Kitty": string;
				"Void Jester Doggy": string;
				"Void PeaceKeeper": string;
				"Royal Bunny": string;
				"Void Ice Cream Pop": string;
				"Radiant Balloon Dragon": string;
				"Void Siphon": string;
				"Void Hellfire Infernum": string;
				"Radiant Radioactive Vision": string;
				"Void Hellfire Hound": string;
				"Radiant Molten Pegasus": string;
				"Jester Narwhal": string;
				"Void Hellfire Ball": string;
				"Radiant Armored Guard": string;
				"Void Gummy Kitty": string;
				"Gear Dragon": string;
				"Void Gummy Dragon": string;
				"Radiant Desert Angel": string;
				"Gear Bunny": string;
				"Void Deer": string;
				"Balloon Dragon": string;
				"Molten Bunny": string;
				"Radiant Hellfire Ball": string;
				"Void Gumdrop": string;
				"Radiant Gummy Doggy": string;
				"Void Googly Chest": string;
				"Void Gear Striker": string;
				PeaceKeeper: string;
				"Radiant Cyber Bear": string;
				"Void Gear Pig": string;
				"Googly Chest": string;
				"Radiant Chromatic Obliterator": string;
				"Radiant Deer": string;
				"Void Cybernetic Guard": string;
				"Void Armored Angel-1": string;
				"City Bunny": string;
				"Void Gear Bunny": string;
				"Radiant Clown Dragon": string;
				"Radiant Desert Demon": string;
				"Molten Pegasus": string;
				"Void Desert Ram": string;
				"Void Molten Blob": string;
				"Void Doggy": string;
				"Void Desert Wraith": string;
				"Void Desert Spider": string;
				"Void Radioactive Imp": string;
				"Void Evil Bee": string;
				"Corrupted Titan": string;
				"Radiant Armored Bunny": string;
				"Gummy Bunny": string;
				"Cyber Bear": string;
				"Radiant Cyber Angel": string;
				"Void Darkness Phoenix": string;
				"Radiant Evil Bee": string;
				"City Defender": string;
				"Cyber Bunny": string;
				"Void D I V I N E": string;
				"Void Cybernetic Phoenix": string;
				"Void Gear Cat": string;
				"Radiant Cyber Doggy": string;
				"Mother Earth": string;
				"Void Cybernetic Destroyer": string;
				"Void Desert Pegasus": string;
				"Radiant Gummy Striker": string;
				"Radiant Gear Dragon": string;
				"Molten Leviathan": string;
				"Void Serene Bunny": string;
				"Radiant Dinosaur Bee": string;
				"Radiant Desert Ram": string;
				"Radioactive Phoenix": string;
				"Radiant Corrupt Duke": string;
				"Radiant Ice Cream Pop": string;
				"Void Cyber Angel": string;
				"Void Corrupted Titan": string;
				"Radiant Corrupt Bunny": string;
				"Void Gummy Bunny-1": string;
				"Hellfire Ball": string;
				"Void Byte": string;
				"500K Doggy": string;
				"Radiant Prime Royal": string;
				"Hellfire Hound": string;
				"Desert Scorpilord": string;
				"Radiant Cybernetic Phoenix": string;
				"Minty Kitty": string;
				"City Angel": string;
				"Bumble Bee": string;
				"Void Corrupt Bear": string;
				"Void Coreye": string;
				"Void Clown Dragon": string;
				"Armored Bunny": string;
				"Void City Kitty": string;
				"500k Wraith": string;
				"Chromatic Obliterator": string;
				"Radiant Radioactive Phoenix": string;
				"Void City Deer": string;
				"Void City Bunny": string;
				"Radiant Cybernetic Destroyer": string;
				"Radiant 500K Doggy": string;
				"Radiant Jester Angel": string;
				"Void City Angel": string;
				"Void Corrupt Pegasus": string;
				"Radiant Corrupt Hyperhalo": string;
				Piggy: string;
				"Radiant Armored Kitty": string;
				"Radiant Seekstress": string;
				"Radiant Armored Pegasus": string;
				"Radiant Corrupted Titan": string;
				"Void Balloon Dragon": string;
				"Radiant Cybernetic Dementor": string;
				"Cybernetic Phoenix": string;
				"Shattered Diety": string;
				Steambot: string;
				"D I V I N E": string;
				"Void Armored Guard": string;
				"Void Armored Doggy": string;
				"Void Supernova Striker": string;
				"Void All Seeing Jester": string;
				"Desert Dragon": string;
				"Void Jester Ghost": string;
				"Mystical Bee": string;
				"Radiant Molten Doggy": string;
				"Armored Kitty": string;
				"Cybernetic Destroyer": string;
				"Void 500K Leviathan": string;
				"Radiant Corrupted Overseer": string;
				"Void 500K Dominus": string;
				"Void 500K Doggy": string;
				"Void 500K Archmage": string;
				"Supreme Dove": string;
				"Radioactive Vision": string;
				"Supernova Striker": string;
				"Radiant Armored Angel": string;
				"Radiant Eternal Gear": string;
				"Corrupt Hyperhalo": string;
				"Radiant Gear Doggy": string;
				"Void Armored Pegasus": string;
				"Molten Destroyer": string;
				"Void Armored Spartan": string;
				"Cyber Angel": string;
				"Serene Bunny": string;
				"Radiant Gummy Dragon": string;
				Seekstress: string;
				"Void Corrupted Overseer": string;
				"Gear Pig": string;
				"Radiant Googly Chest": string;
				"Radiant Hellfire Hound": string;
				"Radioactive Imp": string;
				"Darkness Phoenix": string;
				"Armored Guard": string;
				Angel: string;
				"Radioactive Gryphon": string;
				"Radiant Cyber Bunny": string;
				"Honey Bee": string;
				"Radiant Supernova Striker": string;
				"Radiant Siphon": string;
				"Void Molten Pegasus": string;
				"Radiant Shade Glider": string;
				"Radiant Serene Bunny": string;
				"Radiant Royal Dragon": string;
				"Void City Doggy": string;
				"Radiant Queen Bee": string;
				"Radiant Armored Deer": string;
				"Radiant Developer Gummy Bunny": string;
				"Radiant Molten Wraith": string;
				"Cybernetic Dementor": string;
				"Radiant Molten Squirrel": string;
				"Void Hellfire Dragon": string;
				"Radiant Gear Destroyer": string;
				"Void 500K Ram": string;
				"Radiant Gear Dominus": string;
				"Radiant Desert Dragon": string;
				"Radiant Molten Destroyer": string;
				"Radiant Molten Bunny": string;
				"Radiant 500K Bunny": string;
				"Radiant Gummy Bear": string;
				"Radiant Molten Blob": string;
				Gumdrop: string;
				"Radiant Jester Doggy": string;
				"Gear Doggy": string;
				"Radiant City Doggy": string;
				"Radiant Hychampion": string;
				"Dinosaur Bee": string;
				"Royal Dragon": string;
				"Radiant Hellfire Dragon": string;
				"Royal Pegasus": string;
				"Gummy Kitty": string;
				"Radiant Gummy Wyvern": string;
				"Radiant Gummy Bee": string;
				"Radiant Gumdrop": string;
				"Radiant Gear Striker": string;
				"Radiant Gear Pig": string;
				"Void Cyber Doggy": string;
				"Radiant Molten Kitty": string;
				"Void Armored Bunny": string;
				"Corrupt Duke": string;
				"Radiant Desert Wraith": string;
				"Dark Angel": string;
				"Radiant Desert Spider": string;
				"Radiant Desert Scorpilord": string;
				"Desert Ram": string;
				"Void Gear Destroyer": string;
				"Radiant Coreye": string;
				"City Kitty": string;
				"Radiant Deadly Dark Dominus": string;
				"500K Leviathan": string;
				"Radiant Darkness Phoenix": string;
				"Void Corrupt Hyperhalo": string;
				"Radiant Cybernetic Guard": string;
				"Radiant Cyber Pegasus": string;
				"Void Bumble Bee": string;
				"Void 500K Dragon": string;
				"Radiant Corrupt Doggy": string;
				"Void Royal Dragon": string;
				"Radiant City Deer": string;
				"Radiant City Angel": string;
				"Radiant 500K Ram": string;
				"Radiant Armored Spartan": string;
				"Radiant Piggy": string;
				"Radiant Bunny": string;
				"Radiant 500K Leviathan": string;
				"Gear Dominus": string;
				"Void Bunny Bee": string;
				"Quiet Angel": string;
				"Queen Bee": string;
				"City Doggy": string;
				"Radiant 500K Angel": string;
				"Void Deadly Dark Dominus": string;
				"Molten Blob": string;
				"Void Corrupt Duke": string;
				Mida: string;
				"Gummy Doggy": string;
				"Jester Red Panda": string;
				"Gummy Striker": string;
				"Molten Kitty": string;
				DecalTemplate: string;
				"Void Gear Dragon": string;
				"Void Gummy Doggy": string;
				"Deadly Dark Dominus": string;
				"Eternal Gear": string;
				Deer: string;
				"Corrupt Bunny": string;
				"Void Desert Angel": string;
				"Cyber Kitty": string;
				"Void Molten Destroyer": string;
				"Armored Deer": string;
				"500K Dominus": string;
			};
			worlds: {
				"Ban Land": string;
			};
			gamepasses: {
				"Fast Hatch": string;
				"+2 Pets Equipped": string;
				Teleportation: string;
				"x2 Luck": string;
				"Triple Hatch": string;
				"+3 Pets Equipped": string;
				"+450 Inventory": string;
				"+250 Inventory": string;
				VIP: string;
				Skip_Egg_Hatching: string;
				"x2 Experience": string;
				"x2 Currency": string;
				"+800 Inventory": string;
				"Better Fusion": string;
				"Auto Fight": string;
			};
			weapons: {
				Taliscythe: string;
				"Aquatic Omegablade": string;
				"Spark Plug": string;
				"Stone Smacker": string;
				"Atlantis Basher": string;
				"Crimson Jewel": string;
				"Sunflower Slammer": string;
				"Machine Masher": string;
				"Lime Lance": string;
				"Tropical Lance": string;
				"Carnival Mallet": string;
				"Honey Whacker": string;
				"Sunflower Slicer": string;
				"GearWorx Lance": string;
				"GearWorx Blade": string;
				"Molten Slasher": string;
				"GearWorx Scythe": string;
				"Infernal Staff": string;
				"Dune Glass": string;
				"Amethyst Lance": string;
				"Amethyst Greatblade": string;
				"Candy Lance": string;
				"Sunflower Basher": string;
				"Pillar Slammer": string;
				"Basic Blade": string;
				"Crystalized Hammer": string;
				"Radioactive Greatsword": string;
				"Stinger Scythe": string;
				"Bumble Basher": string;
				"Lava Lance": string;
				"Molten Thrasher": string;
				"Crystalized Scythe": string;
				"Galactic Blade": string;
				"Buzz Blade": string;
				"Radiant Lance": string;
				"Twilight Blade": string;
				"Flower Blade": string;
				"Beach Scythe": string;
				"Buzz Lance": string;
				"Sunflower Sword": string;
				"Samurai Smasher": string;
				"Candy Omegablade": string;
				"Enchanted Scythe": string;
				"Stone Hammer": string;
				"Radiant Smasher": string;
				"Sunflower Spear": string;
				"Gooey Brawler": string;
				"GearWorx Striker": string;
				"Enchanted Lance": string;
				"Radioactive Smasher": string;
				"Radioactive Scythe": string;
				"Radioactive Lance": string;
				"Bomba Bomber": string;
				"Starry Lance": string;
				"Radiant Scythe": string;
				"Gumdrop Dropper": string;
				"Peppermint Scythe": string;
				"Blade Of Mastery": string;
				"Molten Scythe": string;
				"Hellfire Slasher": string;
				"Haunted Blade": string;
				"Enchanted Hammer": string;
				"Atlantis Blade": string;
				"Radiant Greatsword": string;
				"Darkest Desires": string;
				"Forest Slammer": string;
				"Enchanted Greatsword": string;
				"Tropical Thrasher": string;
			};
			talismans: {
				"All Seeing Talisman": string;
				"Awakend Target Talisman": string;
				"Jester Talisman": string;
				"Artifact Skull Talisman": string;
				"Awakend Blade Talisman": string;
				"Artifact Lunar Talisman": string;
				"Artifact Blade Talisman": string;
				"Artifact Star Talisman": string;
				"Awakend GearWorx Talisman": string;
				"Target Talisman": string;
				"Star Talisman": string;
				"Awakend Skull Talisman": string;
				"Artifact Target Talisman": string;
				"Awakend Lunar Talisman": string;
				"Artifact Jester Talisman": string;
				"Artifact All Seeing Talisman": string;
				"Skull Talisman": string;
				"Lunar Talisman": string;
				"Heart Talisman": string;
				"Awakend Star Talisman": string;
				"Artifact GearWorx Talisman": string;
				"GearWorx Talisman": string;
				"Blade Talisman": string;
				"Awakend Jester Talisman": string;
				"Awakend All Seeing Talisman": string;
				"Awakend Heart Talisman": string;
				"Artifact Heart Talisman": string;
			};
			eggs: {
				Honeycomb: string;
				GearWorx: string;
				Candy: string;
				"500K Egg": string;
				"Angelic Egg": string;
				Jester: string;
				Radioactive: string;
				Desert: string;
				"Dweller Egg": string;
				Starter: string;
				Molten: string;
				Royal: string;
			};
		};
		vectors: {
			Egg: string;
			Medal: string;
			StarCoin: string;
			Shield: string;
			Sword: string;
			trading: {
				Wantit: string;
				DontWant: string;
				Downgrade: string;
				Upgrade: string;
				Offer: string;
			};
			currencies: {
				CyberChest: string;
				CoinChest: string;
				GemBag: string;
				CoinPile: string;
				CoinBag: string;
				GemVault: string;
				GemChest: string;
				CoinSafe: string;
				CyberTokenBag: string;
				CyberTokenSafe: string;
				CyberTokenPile: string;
				GemPile: string;
			};
			boosts: {
				blueDouble: string;
				orangeSingle: string;
				orangeTriple: string;
				greenSingle: string;
				blueSingle: string;
				redTriple: string;
				blueCrate: string;
				redDouble: string;
				orangeDouble: string;
				purpleDouble: string;
				redCrate: string;
				greenTriple: string;
				purpleSingle: string;
				purpleTriple: string;
				orangeCrate: string;
				redSingle: string;
				BlueTriple: string;
				purpleCrate: string;
				greenDouble: string;
				greenCrate: string;
			};
			Settings: string;
			Codes: string;
			Gear: string;
			Teleport: string;
			WalkSpeed: string;
			PetPaw: string;
			CyberToken: string;
			Announcement: string;
			Coin: string;
			Robux: string;
			SmallSword: string;
			Rewards: string;
			RedMark: string;
			Trading: string;
			Hammer: string;
			SpinWheel: string;
			Experience: string;
			Lock: string;
			Inventory: string;
			Gem: string;
			Clover: string;
			Error: string;
		};
		ui: {
			egg: {
				background: string;
				"pet frame": string;
				delete: string;
			};
			timeTrials: {
				yellow: string;
				red: string;
				green: string;
			};
			index: {
				view: string;
				extra: string;
				Claim: string;
				returnToSelection: string;
				Off: string;
				sidebar: string;
				eggBackground: string;
				"view challenges": string;
				background: string;
				footerNotice: string;
				showExtraStats: string;
			};
			teleportation: {
				"Candy Land Locked": string;
				"Enchanted Forest": string;
				"Jester Castle Locked": string;
				Desert: string;
				"The Mines": string;
				"Toxic Lands": string;
				"Sunflower Field": string;
				"Desert Locked": string;
				"Candy Land": string;
				exclusive: string;
				"Lava Lands": string;
				background: string;
				"Enchanted Forest Locked": string;
				"Honeycomb Locked": string;
				"The Mines Locked": string;
				Honeycomb: string;
				Beach: string;
				"Beach Locked": string;
				"Ban Land Locked": string;
				"Ice Land": string;
				Forest: string;
				"Toxic Lands Locked": string;
				"Jester Castle": string;
				"Ban Land": string;
				"Lava Lands Locked": string;
				"Forest Locked": string;
				"Ice Land Locked": string;
				"Sunflower Field Locked": string;
				go: string;
			};
			levelup: {
				LevelUp: string;
			};
			shop: {
				accolades: string;
				background: string;
				["biweekly pet"]: string;
				boosts: string;
				currency: string;
				gamepasses: string;
				["limited pets"]: string;
				["playtime rewards"]: string;
			};
			autoDelete: {
				background: string;
				"long green button": string;
				"long red button": string;
			};
			codes: {
				input: string;
				background: string;
			};
			autoFight: {
				minimized: string;
			};
			zones: {
				background: string;
				purchase: string;
				cancel: string;
			};
			"weapon shop": {
				locked: string;
				delete: string;
				"weapon info background": string;
				"purchase button": string;
			};
			"rank upgrade": {
				background: string;
			};
			trading: {
				TradeBackground: string;
				playerSelection: string;
			};
			"update log": {
				"update log": string;
				background: string;
			};
			hud: {
				"interface button": string;
				shop: string;
				upgrade: string;
				"viewer background": string;
				icons: {
					options: string;
					teleport: string;
					rewards: string;
					trading: string;
					items: string;
					shop: string;
					codes: string;
					"auto fight": string;
					wheel: string;
				};
				"rank fill": string;
			};
			talismanTower: {
				sidebar: string;
				background: string;
			};
			settings: {
				"setting background": string;
				background: string;
			};
			equip: {
				unequipped: string;
				keybind: string;
				toolTp: string;
				background: string;
				equipped: string;
			};
			inventory: {
				pets: {
					"unequip all": string;
					"multi-delete disabled": string;
					"inventory size counter icon": string;
					gamepassPrompt: string;
					"delete-sidebar": string;
					sort: string;
					locked: string;
					deleteIndicator: string;
					bottombar: string;
					"pet counter icon": string;
					shrink: string;
					"equipped checkmark": string;
					search: string;
					topbar: string;
					"multi-delete enabled": string;
					maximize: string;
					"function button": string;
				};
				petSummary: string;
				locked: string;
				background: string;
				icons: {
					pets: string;
					weapons: string;
					boosts: string;
					titles: string;
					talismans: string;
				};
				"info sidebar": string;
			};
			quests: {
				"world background": string;
				"world entry background": string;
				"quests background": string;
				"entry background": string;
			};
			account: {
				boostsMastery: string;
				tradeHistory: string;
				editCharacter: string;
				background: string;
				banMastery: string;
				Accolades: string;
				statsBackground: string;
				fusingMastery: string;
				accountMastery: string;
				hatchingMastery: string;
				rankMastery: string;
			};
		};
		ranks: {
			prestiges: {
				Prestige1: string;
				Prestige4: string;
				Prestige3: string;
				Prestige5: string;
				Prestige2: string;
			};
			friendly: {
				Pendulum: string;
				Diamond: string;
				Silver: string;
				Bronze: string;
				Phoenix: string;
				Gold: string;
				Infinitium: string;
				Emerald: string;
				Draconic: string;
				Celestial: string;
			};
			enemy: {
				regular: {
					Diamond: string;
					Silver: string;
					Gold: string;
					Bronze: string;
					Ruby: string;
				};
				boss: {
					Diamond: string;
					Silver: string;
					Gold: string;
					Bronze: string;
					Ruby: string;
				};
			};
		};
	};
}

export = assetIds;
